### ISSUE TITLE
Lost dependence

### ISSUE THREAD

**Issue by soker90** [pyexcel/pyexcel-ods#25]
In version 0.5.0, the "pyexcel" dependency is required to work correctly, but pip does not install it.

I have needed to install pyexcel to write ods files.

**Comment by chfw** [comment]
I had a check. pyexcel and pyexcel-ods do not depend on each other. Only pyexcel-ods depends on pyexcel-io.

**Comment by chfw** [comment]
Here is the architecture:

http://pyexcel.readthedocs.io/en/latest/architecture.html

**Comment by soker90** [comment]
if pyexcel is not installed I get this error

>>> save_data("your_file.ods", data)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/pyexcel_ods/__init__.py", line 30, in save_data
    write_data(afile, data, file_type=file_type, **keywords)
  File "/usr/lib/python3.6/site-packages/pyexcel_io/io.py", line 140, in store_data
    with get_writer(**keywords) as writer:
  File "/usr/lib/python3.6/site-packages/pyexcel_io/io.py", line 213, in get_writer
    writer = WRITERS.get_a_plugin(file_type, library)
  File "/usr/lib/python3.6/site-packages/pyexcel_io/plugins.py", line 77, in get_a_plugin
    plugin = self.load_me_now(__file_type, library=library)
  File "/usr/lib/python3.6/site-packages/lml/plugin.py", line 275, in load_me_now
    cls = self.dynamic_load_library(plugin_info)
  File "/usr/lib/python3.6/site-packages/lml/plugin.py", line 303, in dynamic_load_library
    cls = do_import_class(a_plugin_info.absolute_import_path)
  File "/usr/lib/python3.6/site-packages/lml/utils.py", line 59, in do_import_class
    plugin_module = __import__(plugin_module_name)
  File "/usr/lib/python3.6/site-packages/pyexcel_ods/odsw.py", line 20, in <module>
    import pyexcel_io.service as converter
  File "/usr/lib/python3.6/site-packages/pyexcel_io/service.py", line 14, in <module>
    from pyexcel._compact import PY2
ModuleNotFoundError: No module named 'pyexcel'

In version 0.4 it works

**Comment by chfw** [comment]
Oh I see. It is an unwanted bug

**Comment by chfw** [comment]
Please try pyexcel-io v0.5.1. I have also withdrawn pyexcel-io 0.5.0. Thanks for your report, otherwise I am blinded by my test case, which I will try to correct in the coming days.

**Comment by soker90** [comment]
It works perfectly! Thanks, I've updated the [Archlinux package](https://aur.archlinux.org/packages/python-pyexcel-io/) with the new version.

**Comment by chfw** [comment]
And thanks for bringing pyexcel-io to new world.
